services:
  gateway:
    image: nginx:1.24
    volumes:
      - ./nginx/templates/dev.conf.template:/etc/nginx/templates/default.conf.template:ro
    ports:
      - "23792:80"
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=nicomirror
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=changeme
    ports:
      # Expose port 5432 to allow manual DB connections
      - "5432:5432"
    volumes:
      - ./mnt/postgres-data:/var/lib/postgres/data
      - ./mnt/postgres-init:/docker-entrypoint-initdb.d:ro
  api:
    image: nicomirror-api:latest
    build:
      context: api
    command: uvicorn main:app --reload --host 0.0.0.0 --port 80
    volumes:
      - ./api:/app/nicomirror
    depends_on:
      - db
  # ui:
  # downloader:
  #   depends_on:
  #   - wireguard
  #   network_mode: service:wireguard
  # wireguard:
