services:
  gateway:
    image: nginx:1.24-alpine
    volumes:
      - ./nginx/templates/dev.conf.template:/etc/nginx/templates/default.conf.template:ro
    ports:
      - "80:80"
    depends_on:
      - ui
      - api
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=nicomirror
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=changeme
    ports:
      # Expose port 5432 to allow manual DB connections
      - "5432:5432"
    volumes:
      - ./mnt/postgres-data:/var/lib/postgres/data
      - ./mnt/postgres-init:/docker-entrypoint-initdb.d:ro
  api:
    image: nicomirror-api:latest
    build:
      context: api
    command: uvicorn main:app --reload --host 0.0.0.0 --port 80
    volumes:
      - ./api:/app/nicomirror
    depends_on:
      - db
  ui:
    image: node:18
    working_dir: /app
    command: sh -c "yarn install && yarn start-port80"
    volumes:
      - ./ui/public:/app/public
      - ./ui/src:/app/src
      - ./ui/package.json:/app/package.json
      - ./ui/tsconfig.json:/app/tsconfig.json
      - ./ui/yarn.lock:/app/yarn.lock
      - ./ui/.prettierrc.js:/app/.prettierrc.js
  # downloader:
  #   depends_on:
  #   - wireguard
  #   network_mode: service:wireguard
  # wireguard:
